(function(g){var window=this;var Gpa=function(a,b){return g.Wb(a,b)},H4=function(a,b,c){a.l.set(b,c)},I4=function(a){H4(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.A)()).toString(36));
return a},J4=function(a,b,c){g.La(c)||(c=[String(c)]);
g.Um(a.l,b,c)},Hpa=function(a,b){var c=[];
g.Xi(b,function(d){try{var e=g.En.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ca(e)?g.Dn(e)&&c.push(d):c.push(d)},a);
return c},Ipa=function(a,b){var c=Hpa(a,b);
(0,g.z)(c,function(d){g.En.prototype.remove.call(this,d)},a)},K4=function(a){if(a.Yc){if(a.Yc.locationOverrideToken)return{locationOverrideToken:a.Yc.locationOverrideToken};
if(null!=a.Yc.latitudeE7&&null!=a.Yc.longitudeE7)return{latitudeE7:a.Yc.latitudeE7,longitudeE7:a.Yc.longitudeE7}}return null},Jpa=function(a,b){g.ab(a,b)||a.push(b)},L4=function(a){var b=0,c;
for(c in a)b++;return b},M4=function(a,b){var c=b instanceof g.xc?b:g.Cc(b,/^data:image\//i.test(b));
a.src=g.yc(c)},N4=function(){},Kpa=function(a){try{return g.u.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Lpa=function(a){if(a.wd&&"function"==typeof a.wd)return a.wd();
if(g.Da(a))return a.split("");if(g.Ma(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Sb(a)},Mpa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ma(a)||g.Da(a))(0,g.z)(a,b,void 0);else{if(a.Wd&&"function"==typeof a.Wd)var c=a.Wd();else if(a.wd&&"function"==typeof a.wd)c=void 0;else if(g.Ma(a)||g.Da(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Tb(a);d=Lpa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},Npa=function(a,b,c,d){var e=new g.Im(null,void 0);
a&&g.Jm(e,a);b&&g.Km(e,b);c&&g.Lm(e,c);d&&(e.i=d);return e},O4=function(a,b){g.Go[a]=!0;
var c=g.Eo();c&&c.publish.apply(c,arguments);g.Go[a]=!1},P4=function(a){try{var b=(0,g.Tx)(),c=(0,g.Sx)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},Opa=function(){var a=(0,g.Sx)();
a&&Ipa(a,a.g.af(!0))},Q4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Fm;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Ppa(this,a.capabilities||""),Qpa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},Ppa=function(a,b){a.capabilities.clear();
(0,g.Vd)(b.split(","),g.Ra(Gpa,Rpa)).forEach(function(c){a.capabilities.add(c)})},Qpa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},R4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},S4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},T4=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Spa=function(a){return new R4(a)},U4=function(a){return g.La(a)?(0,g.ee)(a,Spa):[]},V4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},W4=function(a){return g.La(a)?"["+(0,g.ee)(a,V4).join(",")+"]":"null"},X4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Tpa=function(a){return(0,g.ee)(a,function(b){return{key:b.id,
name:b.name}})},Y4=function(a,b){return g.Ya(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},Z4=function(a,b){return g.Ya(a,function(c){return S4(c,b)})},$4=function(){var a=g.Vx("yt-remote-connected-devices")||[];
g.rb(a);return a},Upa=function(a){if(g.bb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.ee)(a,function(d,e){return 0==e?d:d.substring(c.length)})},a5=function(a){g.Ux("yt-remote-connected-devices",a,86400)},c5=function(){if(b5)return b5;
var a=g.Vx("yt-remote-device-id");a||(a=X4(),g.Ux("yt-remote-device-id",a,31536E3));for(var b=$4(),c=1,d=a;g.ab(b,d);)c++,d=a+"#"+c;return b5=d},d5=function(){var a=$4(),b=c5();
g.ab(a,b);g.ZK()&&g.tb(a,b);a=Upa(a);if(g.bb(a))try{g.tr("remote_sid")}catch(c){}else try{g.sr("remote_sid",a.join(","),-1)}catch(c){}},e5=function(){return g.Vx("yt-remote-session-browser-channel")},f5=function(){return g.Vx("yt-remote-local-screens")||[]},g5=function(){g.Ux("yt-remote-lounge-token-expiration",!0,86400)},Vpa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.ee)(f5(),function(d){return d.loungeToken}),c=(0,g.ee)(a,function(d){return d.loungeToken});
(0,g.Xg)(c,function(d){return!g.ab(b,d)})&&g5();
g.Ux("yt-remote-local-screens",a,31536E3)},Wpa=function(a,b){g.Ux("yt-remote-session-browser-channel",a);
g.Ux("yt-remote-session-screen-id",b);var c=$4(),d=c5();g.ab(c,d)||c.push(d);a5(c);d5()},h5=function(a){a||(P4("yt-remote-session-screen-id"),P4("yt-remote-session-video-id"));
d5();a=$4();g.eb(a,c5());a5(a)},j5=function(){if(!i5){var a=g.On();
a&&(i5=new g.yn(a))}return i5?!!i5.get("yt-remote-use-staging-server"):!1},k5=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},l5=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},n5=function(a){a.length?m5(a.shift(),function(){n5(a)}):o5()},Xpa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},m5=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},o5=function(){var a=l5();
a&&a(!1,"No cast extension found")},p5=function(){if(Ypa){var a=2,b=l5(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;m5("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",o5,c)}},Zpa=function(){p5();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);n5(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},q5=function(a,b,c){g.F.call(this);
this.w=null!=c?(0,g.x)(a,c):a;this.Rc=b;this.u=(0,g.x)(this.WB,this);this.g=!1;this.i=0;this.l=this.za=null;this.o=[]},r5=function(a){if(g.u.JSON)try{return g.u.JSON.parse(a)}catch(b){}return Kpa(a)},s5=function(){},t5=function(){},u5=function(){},w5=function(a){return(a=v5(a))?new ActiveXObject(a):new XMLHttpRequest},v5=function(a){if(!a.i&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.i=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.i},x5=function(a,b,c,d){this.g=a;
this.l=b;this.B=c;this.w=d||1;this.o=45E3;this.ba=new g.$Y(this);this.i=new g.el;this.i.setInterval(250)},z5=function(a,b,c){a.Jh=1;
a.Kf=I4(b.clone());a.eh=c;a.u=!0;y5(a,null)},A5=function(a,b,c,d,e){a.Jh=1;
a.Kf=I4(b.clone());a.eh=null;a.u=c;e&&(a.Zy=!1);y5(a,d)},y5=function(a,b){a.oi=(0,g.A)();
B5(a);a.rg=a.Kf.clone();J4(a.rg,"t",a.w);a.Ek=0;a.pc=a.g.Qo(a.g.qk()?b:null);0<a.wp&&(a.fn=new g.hl((0,g.x)(a.Yz,a,a.pc),a.wp));a.ba.ea(a.pc,"readystatechange",a.RK);var c=a.Mg?g.bc(a.Mg):{};a.eh?(a.Mn="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.pc.send(a.rg,a.Mn,a.eh,c)):(a.Mn="GET",a.Zy&&!g.Ld&&(c.Connection="close"),a.pc.send(a.rg,a.Mn,null,c));a.g.me(1)},I5=function(a,b,c){for(var d=!0;!a.Bg&&a.Ek<c.length;){var e=$pa(a,c);
if(e==C5){4==b&&(a.cg=4,D5(15),d=!1);break}else if(e==E5){a.cg=4;D5(16);d=!1;break}else F5(a,e)}4==b&&0==c.length&&(a.cg=1,D5(17),d=!1);a.ne=a.ne&&d;d||(G5(a),H5(a))},$pa=function(a,b){var c=a.Ek,d=b.indexOf("\n",c);
if(-1==d)return C5;c=Number(b.substring(c,d));if(isNaN(c))return E5;d+=1;if(d+c>b.length)return C5;var e=b.substr(d,c);a.Ek=d+c;return e},L5=function(a,b){a.oi=(0,g.A)();
B5(a);var c=b?window.location.hostname:"";a.rg=a.Kf.clone();H4(a.rg,"DOMAIN",c);H4(a.rg,"t",a.w);try{a.re=new ActiveXObject("htmlfile")}catch(n){G5(a);a.cg=7;D5(22);H5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in J5)k=J5[l];else if(l in K5)k=J5[l]=K5[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
J5[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Qc(g.qc("b/12014412"),d+"</body></html>");a.re.open();a.re.write(g.Lc(c));a.re.close();a.re.parentWindow.m=(0,g.x)(a.gK,a);a.re.parentWindow.d=(0,g.x)(a.hy,a,!0);a.re.parentWindow.rpcClose=(0,g.x)(a.hy,a,!1);c=a.re.createElement("DIV");a.re.parentWindow.document.body.appendChild(c);d=g.Bc(a.rg.toString());d=g.Zc(g.zc(d));d=g.Qc(g.qc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Rc(c,d);a.g.me(1)},B5=function(a){a.ks=(0,g.A)()+a.o;
M5(a,a.o)},M5=function(a,b){if(null!=a.Fi)throw Error("WatchDog timer not null");
a.Fi=N5((0,g.x)(a.pK,a),b)},O5=function(a){a.Fi&&(g.u.clearTimeout(a.Fi),a.Fi=null)},H5=function(a){a.g.av()||a.Bg||a.g.Xm(a)},G5=function(a){O5(a);
g.Ai(a.fn);a.fn=null;a.i.stop();g.bZ(a.ba);if(a.pc){var b=a.pc;a.pc=null;b.abort();b.dispose()}a.re&&(a.re=null)},F5=function(a,b){try{a.g.ay(a,b),a.g.me(4)}catch(c){}},Q5=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;P5(a,b,function(k){k?c(!0):g.u.setTimeout(function(){Q5(a,b,c,d,f)},f)})}},P5=function(a,b,c){var d=new Image;
d.onload=function(){try{R5(d),c(!0)}catch(e){}};
d.onerror=function(){try{R5(d),c(!1)}catch(e){}};
d.onabort=function(){try{R5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{R5(d),c(!1)}catch(e){}};
g.u.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
M4(d,a)},R5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},S5=function(a){this.g=a;
this.i=new s5},U5=function(a){var b=T5(a.g,a.Ri,"/mail/images/cleardot.gif");
I4(b);Q5(b.toString(),5E3,(0,g.x)(a.bB,a),3,2E3);a.me(1)},W5=function(a){var b=a.g.D;
if(null!=b)D5(5),b?(D5(11),V5(a.g,a,!1)):(D5(12),V5(a.g,a,!0));else if(a.Ad=new x5(a,void 0,void 0,void 0),a.Ad.Mg=a.tp,b=a.g,b=T5(b,b.qk()?a.qj:null,a.vp),D5(5),!g.Jd||g.od(10))J4(b,"TYPE","xmlhttp"),A5(a.Ad,b,!1,a.qj,!1);else{J4(b,"TYPE","html");var c=a.Ad;a=!!a.qj;c.Jh=3;c.Kf=I4(b.clone());L5(c,a)}},X5=function(a){g.uk.call(this);
this.headers=new g.Fm;this.M=a||null;this.l=!1;this.R=this.g=null;this.W=this.D="";this.w=0;this.o="";this.u=this.aa=this.C=this.P=!1;this.B=0;this.G=null;this.X="";this.I=this.S=!1},aqa=function(a){return g.Jd&&g.ld(9)&&g.Fa(a.timeout)&&g.Ca(a.ontimeout)},bqa=function(a){return"content-type"==a.toLowerCase()},$5=function(a,b){a.l=!1;
a.g&&(a.u=!0,a.g.abort(),a.u=!1);a.o=b;a.w=5;Y5(a);Z5(a)},Y5=function(a){a.P||(a.P=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},c6=function(a){if(a.l&&"undefined"!=typeof g.fZ)if(a.R[1]&&4==a6(a)&&2==a.getStatus())b6(a,"Local request error detected and ignored");
else if(a.C&&4==a6(a))g.fl(a.cv,0,a);else if(a.dispatchEvent("readystatechange"),4==a6(a)){b6(a,"Request complete");a.l=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.tf(1,String(a.D));if(!f&&g.u.self&&g.u.self.location){var k=g.u.self.location.protocol;f=k.substr(0,k.length-1)}e=!cqa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.w=6;try{var l=2<a6(a)?a.g.statusText:""}catch(m){l=""}a.o=l+" ["+a.getStatus()+"]";Y5(a)}}finally{Z5(a)}}},Z5=function(a,b){if(a.g){d6(a);
var c=a.g,d=a.R[0]?g.Ia:null;a.g=null;a.R=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},d6=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.G&&(g.u.clearTimeout(a.G),a.G=null)},a6=function(a){return a.g?a.g.readyState:0},e6=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},b6=function(a,b){return b+" ["+a.W+" "+a.D+" "+a.getStatus()+"]"},f6=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new s5;this.C=a||null;this.D=null!=b?b:null;this.w=c||!1},dqa=function(a,b){this.g=a;
this.map=b;this.context=null},g6=function(a){g.Xj.call(this,"statevent",a)},h6=function(a,b){g.Xj.call(this,"timingevent",a);
this.size=b},i6=function(a){g.Xj.call(this,"serverreachability",a)},m6=function(a){j6(a);
if(3==a.g){var b=a.Wj++,c=a.Fl.clone();H4(c,"SID",a.l);H4(c,"RID",b);H4(c,"TYPE","terminate");k6(a,c);b=new x5(a,a.l,b,void 0);b.Jh=2;b.Kf=I4(c.clone());M4(new Image,b.Kf.toString());b.oi=(0,g.A)();B5(b)}l6(a)},o6=function(a){a.vB(1,0);
a.Fl=T5(a,null,a.rp);n6(a)},j6=function(a){a.Qf&&(a.Qf.abort(),a.Qf=null);
a.Nb&&(a.Nb.cancel(),a.Nb=null);a.bf&&(g.u.clearTimeout(a.bf),a.bf=null);p6(a);a.td&&(a.td.cancel(),a.td=null);a.Xf&&(g.u.clearTimeout(a.Xf),a.Xf=null)},q6=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new dqa(a.vG++,b));2!=a.g&&3!=a.g||n6(a)},n6=function(a){a.td||a.Xf||(a.Xf=N5((0,g.x)(a.gy,a),0),a.Ch=0)},t6=function(a,b){if(1==a.g){if(!b){a.Wj=Math.floor(1E5*Math.random());
var c=a.Wj++,d=new x5(a,"",c,void 0);d.Mg=null;var e=r6(a),f=a.Fl.clone();H4(f,"RID",c);H4(f,"CVER","1");k6(a,f);z5(d,f,e);a.td=d;a.g=2}}else 3==a.g&&(b?s6(a,b):0==a.i.length||a.td||s6(a))},s6=function(a,b){if(b)if(6<a.Cg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.Wj-1;var d=r6(a)}else c=b.B,d=b.eh;else c=a.Wj++,d=r6(a);var e=a.Fl.clone();H4(e,"SID",a.l);H4(e,"RID",c);H4(e,"AID",a.Vh);k6(a,e);c=new x5(a,a.l,c,a.Ch+1);c.Mg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.td=c;z5(c,e,d)},k6=function(a,b){if(a.Oc){var c=a.Oc.Du();
c&&g.Mb(c,function(d,e){H4(b,e,d)})}},r6=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Cg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Cg?e:f-d;try{g.Mb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},u6=function(a){a.Nb||a.bf||(a.B=1,a.bf=N5((0,g.x)(a.fy,a),0),a.wh=0)},w6=function(a){if(a.Nb||a.bf||3<=a.wh)return!1;
a.B++;a.bf=N5((0,g.x)(a.fy,a),v6(a,a.wh));a.wh++;return!0},V5=function(a,b,c){a.Kn=c;
a.we=b.qf;a.w||o6(a)},p6=function(a){null!=a.Fg&&(g.u.clearTimeout(a.Fg),a.Fg=null)},v6=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},y6=function(a,b){if(2==b||9==b){var c=null;
a.Oc&&(c=null);var d=(0,g.x)(a.xL,a);c||(c=new g.Im("//www.google.com/images/cleardot.gif"),I4(c));P5(c.toString(),1E4,d)}else D5(2);x6(a,b)},x6=function(a,b){a.g=0;
a.Oc&&a.Oc.Pt(b);l6(a);j6(a)},l6=function(a){a.g=0;
a.we=-1;if(a.Oc)if(0==a.o.length&&0==a.i.length)a.Oc.Jo();else{g.ib(a.o);var b=g.ib(a.i);a.o.length=0;a.i.length=0;a.Oc.Jo(b)}},T5=function(a,b,c){var d=g.Qm(c);
if(""!=d.g)b&&g.Km(d,b+"."+d.g),g.Lm(d,d.u);else{var e=window.location;d=Npa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.dj&&g.Mb(a.dj,function(f,k){H4(d,k,f)});
H4(d,"VER",a.Cg);k6(a,d);return d},N5=function(a,b){if(!g.Na(a))throw Error("Fn must not be null and must be a function");
return g.u.setTimeout(function(){a()},b)},D5=function(a){z6.dispatchEvent(new g6(z6,a))},A6=function(){},B6=function(){this.g=[];
this.i=[]},eqa=function(a,b){this.action=a;
this.params=b||{}},C6=function(a,b){g.F.call(this);
this.g=new g.I(this.XJ,0,this);g.H(this,this.g);this.Rc=5E3;this.i=0;if(g.Na(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Na(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},D6=function(a,b,c){this.G=a;
this.w=b;this.l=new g.xn;this.i=new C6(this.bL,this);this.g=null;this.bb=!1;this.u=null;this.D="";this.C=this.o=0;this.B=[];this.I=c||!1},fqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Kn,sessionId:a.g.l,arrayId:a.g.Vh}},E6=function(a,b){a.C=b||0;
a.i.stop();a.g&&(3==a.g.g&&t6(a.g),m6(a.g));a.C=0},F6=function(a){return!!a.g&&3==a.g.g},gqa=function(a,b){(a.w.loungeIdToken=b)||a.i.stop()},G6=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.tf(4,a))||"";b&&(this.port=":"+b);this.domain=g.uf(a)||"";a=g.Kb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Jb(a,"10.0")&&(this.i=!1))},H6=function(a,b){var c=a.g;
if(g.Ca(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.Df(c+b,{})},I6=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ra(a.o,d,!0),onError:g.Ra(a.l,e),Nd:g.Ra(a.u,e)};c&&(a.rb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.zp(b,a)},hqa=function(){var a=J6;
K6();L6.push(a);M6(L6)},N6=function(a,b){K6();
var c=L6,d=iqa(a,String(b));g.bb(c)?jqa(d):(M6(c),(0,g.z)(c,function(e){e(d)}))},K6=function(){L6||(L6=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",L6,void 0))},jqa=function(a){var b=(O6+1)%50;
O6=b;P6[b]=a;Q6||(Q6=49==b)},M6=function(a){var b=P6;
if(b[0]){var c=O6,d=Q6?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.z)(a,function(f){f(e)})}while(d!=c);
P6=Array(50);O6=-1;Q6=!1}},iqa=function(a,b){var c=((0,g.A)()-kqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},R6=function(a){g.O.call(this);
this.B=a;this.g=[]},S6=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},lqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Vd)(a.g,function(f){return!!Y4(b,f)});
for(var d=0,e=b.length;d<e;d++)c=S6(a,b[d])||c;return c},mqa=function(a,b){var c=a.g.length;
a.g=(0,g.Vd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},T6=function(a,b,c,d){g.O.call(this);
this.w=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.za=NaN},V6=function(a){R6.call(this,"LocalScreenService");
this.l=a;this.i=NaN;U6(this);this.info("Initializing with "+W4(this.g))},W6=function(a){if(a.g.length){var b=(0,g.ee)(a.g,function(d){return d.id}),c=H6(a.l,"/pairing/get_lounge_token_batch");
I6(a.l,c,{screen_ids:b.join(",")},(0,g.x)(a.hC,a),(0,g.x)(a.gC,a))}},U6=function(a){var b=U4(f5());
b=(0,g.Vd)(b,function(c){return!c.uuid});
return lqa(a,b)},X6=function(a,b){Vpa((0,g.ee)(a.g,T4));
b&&g5()},Z6=function(a,b){g.O.call(this);
this.w=b;var c=g.Vx("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.w(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.ab(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;Y6("Initialized with "+g.Bj(this.g))},$6=function(a,b,c){var d=H6(a.u,"/pairing/get_screen_availability");
I6(a.u,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},a7=function(a,b){a:if(L4(b)!=L4(a.g))var c=!1;
else{c=g.Tb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(Y6("Updated online screens: "+g.Bj(a.g)),a.g=b,a.N("screenChange"));nqa(a)},b7=function(a){isNaN(a.l)||g.Do(a.l);
a.l=g.Bo((0,g.x)(a.ur,a),0<a.o&&a.o<(0,g.A)()?2E4:1E4)},Y6=function(a){N6("OnlineScreenService",a)},c7=function(a){var b={};
(0,g.z)(a.w(),function(c){c.token?b[c.token]=c.id:this.Gb("Requesting availability of screen w/o lounge token.")});
return b},nqa=function(a){a=g.Tb(g.Nb(a.g,function(b){return b}));
g.rb(a);a.length?g.Ux("yt-remote-online-screen-ids",a.join(","),60):P4("yt-remote-online-screen-ids")},d7=function(a){R6.call(this,"ScreenService");
this.w=a;this.i=this.l=null;this.o=[];this.u={};oqa(this)},f7=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Kd();if(k=(c?Z4(k,c):null)||Z4(k,b)){k.uuid=b;var l=e7(a,k);$6(a.i,l,function(m){e(m?l:null)})}else c?pqa(a,c,(0,g.x)(function(m){var n=e7(this,new R4({name:d,
screenId:c,loungeToken:m,dialId:b||""}));$6(this.i,n,function(q){e(q?n:null)})},a),f):e(null)},g7=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},pqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={rb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.zp(H6(a.w,"/pairing/get_lounge_token_batch"),e)},h7=function(a){a.g=a.l.Kd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+W4(a.g))},oqa=function(a){i7(a);
a.l=new V6(a.w);a.l.subscribe("screenChange",(0,g.x)(a.oC,a));h7(a);a.o=U4(g.Vx("yt-remote-automatic-screen-cache")||[]);i7(a);a.info("Initializing automatic screens: "+W4(a.o));a.i=new Z6(a.w,(0,g.x)(a.Kd,a,!0));a.i.subscribe("screenChange",(0,g.x)(function(){this.N("onlineScreenChange")},a))},e7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=Z4(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.Ux("yt-remote-automatic-screen-cache",(0,g.ee)(a.o,T4)));i7(a);a.u[b.uuid]=b.id;g.Ux("yt-remote-device-id-map",a.u,31536E3);return b},i7=function(a){a.u=g.Vx("yt-remote-device-id-map")||{}},j7=function(a,b,c){g.O.call(this);
this.R=c;this.D=a;this.i=b;this.l=null},k7=function(a,b){N6(a.R,b)},m7=function(a,b){j7.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.w=(0,g.x)(this.dM,this);this.u=(0,g.x)(this.AK,this);this.o=g.Bo((0,g.x)(function(){l7(this,null)},this),12E4)},qqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Bj(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ia,(0,g.x)(function(){k7(this,"Failed to send message: getMdxSessionStatus.")},a)):k7(a,"Sending yt message without session: "+g.Bj(b))},l7=function(a,b){g.Do(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.x)(a.Zm,a),d=(0,g.x)(a.Md,a);a.Vu(b,c,d,5)}}else a.Md(Error("Waiting for session status timed out."))},n7=function(a,b,c){j7.call(this,a,b,"DialSession");
this.o=this.C=null;this.G="";this.M=c;this.u=null;this.B=g.Ia;this.w=NaN;this.I=(0,g.x)(this.gM,this);this.g=g.Ia},o7=function(a){a.g=a.D.eA(a.G,a.i.label,a.i.friendlyName,(0,g.x)(function(b){this.g=g.Ia;
this.Zm(b)},a),(0,g.x)(function(b){this.g=g.Ia;
this.Md(b)},a))},p7=function(a){var b={};
b.pairingCode=a.G;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}j5()&&(b.env_useStageMdx=1);return g.Bf(b)},q7=function(a,b){j7.call(this,a,b,"ManualSession");
this.g=g.Bo((0,g.x)(this.Wh,this,null),150)},r7=function(a,b,c,d){g.O.call(this);
this.i=a;this.B=b||"233637DE";this.w=c||"cl";this.C=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.x)(this.gJ,this)},s7=function(a,b){return b?g.Ya(a.l,function(c){return S4(b,c.label)},a):null},t7=function(a){N6("Controller",a)},J6=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},u7=function(a){return a.u||!!a.l.length||!!a.g},v7=function(a,b,c){b!=a.g&&(g.Ai(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.x)(a.ey,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.Wh(null)):a.N("yt-remote-cast2-session-change",null))},w7=function(a){var b=a.i.dA(),c=a.g&&a.g.i;
a=(0,g.ee)(b,function(d){c&&S4(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=s7(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},uqa=function(a,b,c,d,e,f,k){rqa()?sqa(b,e,f,k)&&(y7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?z7(a,c):(window.__onGCastApiAvailable=function(l,m){l?z7(a,c):(A7("Failed to load cast API: "+m),B7(!1),y7(!1),P4("yt-remote-cast-available"),P4("yt-remote-cast-receiver"),C7(),c(!1))},d?g.Oo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Zpa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?o5():(p5(),n5(tqa.map(Xpa))))):x7("Cannot initialize because not running Chrome")},C7=function(){x7("dispose");
var a=D7();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);E7(!1);g.Jo(F7);F7.length=0},G7=function(){return!!g.Vx("yt-remote-cast-installed")},H7=function(){var a=g.Vx("yt-remote-cast-receiver");
return a?a.friendlyName:null},I7=function(){x7("clearCurrentReceiver");
P4("yt-remote-cast-receiver")},J7=function(){return G7()?D7()?D7().getCastSession():(A7("getCastSelector: Cast is not initialized."),null):(A7("getCastSelector: Cast API is not installed!"),null)},L7=function(){G7()?D7()?K7()?(x7("Requesting cast selector."),D7().requestSession()):(x7("Wait for cast API to be ready to request the session."),F7.push(g.Io("yt-remote-cast2-api-ready",L7))):A7("requestCastSelector: Cast is not initialized."):A7("requestCastSelector: Cast API is not installed!")},M7=function(a,
b){K7()?D7().setConnectedScreenStatus(a,b):A7("setConnectedScreenStatus called before ready.")},rqa=function(){var a=0<=g.Kb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Bs||a},vqa=function(a,b){D7().init(a,b)},sqa=function(a,b,c,d){var e=!1;
D7()||(a=new r7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Ux("yt-remote-cast-available",f);O4("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){x7("onReceiverSelected: "+f.friendlyName);
g.Ux("yt-remote-cast-receiver",f);O4("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){x7("onReceiverResumed: "+f.friendlyName);
g.Ux("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){x7("onSessionChange: "+V4(f));
f||P4("yt-remote-cast-receiver");O4("yt-remote-cast2-session-change",f)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
x7("cloudview.createSingleton_: "+e);return e},D7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},z7=function(a,b){B7(!0);
y7(!1);vqa(a,function(c){c?(E7(!0),g.Lo("yt-remote-cast2-api-ready")):(A7("Failed to initialize cast API."),B7(!1),P4("yt-remote-cast-available"),P4("yt-remote-cast-receiver"),C7());b(c)})},x7=function(a){N6("cloudview",a)},A7=function(a){N6("cloudview",a)},B7=function(a){x7("setCastInstalled_ "+a);
g.Ux("yt-remote-cast-installed",a)},K7=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},E7=function(a){x7("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},y7=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},N7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.w=this.B=0;this.g=null;this.hasNext=this.xe=!1;this.D=this.C=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},O7=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.xe=!1;a.hasNext=!1;a.B=0;a.w=(0,g.A)();a.o=0;a.i=0;a.C=0;a.D=0;a.l=NaN;a.u=!1},P7=function(a){return 1==a.playerState?((0,g.A)()-a.w)/1E3:0},Q7=function(a,b){a.B=b;
a.w=(0,g.A)()},R7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.A)()-a.w)/1E3+a.B;
case -1E3:return 0}return a.B},S7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&O7(a)},T7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.g);b.hasPrevious=a.xe;b.hasNext=a.hasNext;b.playerTime=a.B;b.playerTimeAt=a.w;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.C;b.loadedTime=a.D;b.liveIngestionTime=a.l;return b},W7=function(a,b){g.O.call(this);
this.g=0;this.o=a;this.w=[];this.u=new B6;this.l=this.i=null;this.D=(0,g.x)(this.dH,this);this.B=(0,g.x)(this.Zj,this);this.C=(0,g.x)(this.cH,this);this.G=(0,g.x)(this.pH,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.qs,this),U7(this))):c=3;0!=c&&(b?this.qs(c):g.Bo((0,g.x)(function(){this.qs(c)},this),0));
var d=J7();d&&V7(this,d);this.subscribe("yt-remote-cast2-session-change",this.G)},X7=function(a){return new N7(a.o.getPlayerContextData())},U7=function(a){(0,g.z)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.w.push(this.o.subscribe(b,g.Ra(this.dJ,b),this))},a)},Y7=function(a){(0,g.z)(a.w,function(b){this.o.unsubscribeByKey(b)},a);
a.w.length=0},Z7=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},a8=function(a,b,c){var d=X7(a);
Q7(d,c);-1E3!=d.playerState&&(d.playerState=b);$7(a,d)},b8=function(a,b,c){a.o.sendMessage(b,c)},$7=function(a,b){Y7(a);
a.o.setPlayerContextData(T7(b));U7(a)},V7=function(a,b){a.l&&(a.l.removeUpdateListener(a.D),a.l.removeMediaListener(a.B),a.Zj(null));
a.l=b;a.l&&(N6("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.D),a.l.addMediaListener(a.B),a.l.media.length&&a.Zj(a.l.media[0]))},c8=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=X7(a);b.contentId!=d.videoId&&N6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;Q7(d,a.i.getEstimatedTime());$7(a,d)}else N6("CP","No cast media video. Ignoring state update.")},d8=function(a,b,c){return(0,g.x)(function(d){this.Gb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Gb("Retrying "+b+" using MDx browser channel."),b8(this,b,c))},a)},e8=function(a,b,c){g.O.call(this);
this.u=NaN;this.I=!1;this.C=this.B=this.D=this.G=NaN;this.R=[];this.o=this.w=this.l=this.Oa=this.g=null;this.P=a;this.R.push(g.Yq(window,"beforeunload",(0,g.x)(this.ZB,this)));this.i=[];this.Oa=new N7;this.M=b.id;this.g=wqa(this,c);this.g.subscribe("handlerOpened",this.hH,this);this.g.subscribe("handlerClosed",this.eH,this);this.g.subscribe("handlerError",this.fH,this);this.g.subscribe("handlerMessage",this.gH,this);gqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Oa.videoId;
g.ZK()&&g.Ux("yt-remote-session-video-id",d)},this)},f8=function(a){N6("conn",a)},wqa=function(a,b){return new D6(H6(a.P,"/bc"),b)},g8=function(a,b){a.N("proxyStateChange",b)},xqa=function(a){a.u=g.Bo((0,g.x)(function(){f8("Connecting timeout");
this.Ah(1)},a),2E4)},h8=function(a){g.Do(a.u);
a.u=NaN},i8=function(a){g.Do(a.G);
a.G=NaN},yqa=function(a){j8(a);
a.D=g.Bo((0,g.x)(function(){k8(this,"getNowPlaying")},a),2E4)},j8=function(a){g.Do(a.D);
a.D=NaN},m8=function(a,b){b&&(h8(a),i8(a));
b==(F6(a.g)&&isNaN(a.u))?b&&(g8(a,1),k8(a,"getSubtitlesTrack")):b?(a.Tu()&&a.Oa.reset(),g8(a,1),k8(a,"getNowPlaying"),l8(a)):a.Ah(1)},zqa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Oa.videoId&&(g.Zb(b.params)?a.Oa.g=null:a.Oa.g=b.params,a.N("remotePlayerChange"))},n8=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Oa.listId=b.params.listId||a.Oa.listId;S7(a.Oa,c,d);a.N("remoteQueueChange")},Aqa=function(a,b){b.params=b.params||{};
n8(a,b);o8(a,b);a.N("autoplayDismissed")},o8=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
Q7(a.Oa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Oa.playerState&&(c=-1E3);a.Oa.playerState=c;c=Number(b.params.loadedTime);a.Oa.D=isNaN(c)?0:c;c=Number(b.params.duration);a.Oa.C=isNaN(c)?0:c;c=a.Oa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Oa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Oa.playerState?yqa(a):j8(a);a.N("remotePlayerChange")},Bqa=function(a,b){if(-1E3!=
a.Oa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Oa.playerState=c;c=parseInt(b.params.currentTime,10);Q7(a.Oa,isNaN(c)?0:c);a.N("remotePlayerChange")}},Cqa=function(a,b){var c="true"==b.params.muted;
a.Oa.volume=parseInt(b.params.volume,10);a.Oa.muted=c;a.N("remotePlayerChange")},Dqa=function(a,b){a.w=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},Eqa=function(a,b){var c="true"==b.params.hasNext;
a.Oa.xe="true"==b.params.hasPrevious;a.Oa.hasNext=c;a.N("previousNextChange")},l8=function(a){g.Do(a.C);
a.C=g.Bo((0,g.x)(a.Ah,a,1),864E5)},k8=function(a,b,c){c?f8("Sending: action="+b+", params="+g.Bj(c)):f8("Sending: action="+b);
a.g.sendMessage(b,c)},p8=function(a){R6.call(this,"ScreenServiceProxy");
this.Qc=a;this.i=[];this.i.push(this.Qc.$_s("screenChange",(0,g.x)(this.bM,this)));this.i.push(this.Qc.$_s("onlineScreenChange",(0,g.x)(this.GI,this)))},Jqa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.to("MDX_CONFIG")||b;Opa();d5();q8||(q8=new G6(b?b.loungeApiHost:void 0),j5()&&(q8.g="/api/loungedev"));r8||(r8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",r8,void 0));Fqa();var c=s8();if(!c){var d=new d7(q8);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=s8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);uqa(a,d,function(m){m?t8()&&M7(t8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){O4("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),u8("Initializing: "+g.Bj(b)),v8.push(g.Io("yt-remote-cast2-availability-change",function(){O4("yt-remote-receiver-availability-change")})),v8.push(g.Io("yt-remote-cast2-receiver-selected",function(){w8(null);
O4("yt-remote-auto-connect","cast-selector-receiver")})),v8.push(g.Io("yt-remote-cast2-receiver-resumed",function(){O4("yt-remote-receiver-resumed","cast-selector-receiver")})),v8.push(g.Io("yt-remote-cast2-session-change",Gqa)),v8.push(g.Io("yt-remote-connection-change",function(m){m?M7(t8(),"YouTube TV"):x8()||(M7(null,null),I7())})),a=y8(),b.isAuto&&(a.id+="#dial"),g.qp("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),u8(" -- with channel params: "+
g.Bj(a)),Hqa(a),c.start(),t8()||Iqa())},Kqa=function(){var a=z8();
G7()&&g.Vx("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},z8=function(){var a=s8().Qc.$_gos();
var b=A8();b&&B8()&&(Y4(a,b)||a.push(b));return Tpa(a)},C8=function(){var a=Lqa();
!a&&G7()&&H7()&&(a={key:"cast-selector-receiver",name:H7()});return a},Lqa=function(){var a=z8(),b=A8();
b||(b=x8());return g.Ya(a,function(c){return b&&S4(b,c.key)?!0:!1})},A8=function(){var a=t8();
if(!a)return null;var b=s8().Kd();return Z4(b,a)},Gqa=function(a){u8("remote.onCastSessionChange_: "+V4(a));
if(a){var b=A8();b&&b.id==a.id?M7(b.id,"YouTube TV"):(b&&D8(),E8(a,1))}else B8()&&D8()},D8=function(){K7()?D7().stopSession():A7("stopSession called before API ready.");
var a=B8();a&&(a.disconnect(1),F8(null))},G8=function(){var a=B8();
return!!a&&3!=a.getProxyState()},u8=function(a){N6("remote",a)},s8=function(){if(!H8){var a=g.w("yt.mdx.remote.screenService_");
H8=a?new p8(a):null}return H8},t8=function(){return g.w("yt.mdx.remote.currentScreenId_")},I8=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},J8=function(){return g.w("yt.mdx.remote.connectData_")},w8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},B8=function(){return g.w("yt.mdx.remote.connection_")},F8=function(a){var b=B8();
w8(null);a||I8("");g.Ga("yt.mdx.remote.connection_",a,void 0);r8&&((0,g.z)(r8,function(c){c(a)}),r8.length=0);
b&&!a?O4("yt-remote-connection-change",!1):!b&&a&&O4("yt-remote-connection-change",!0)},x8=function(){var a=g.ZK();
if(!a)return null;var b=s8().Kd();return Z4(b,a)},E8=function(a,b){A8()&&A8();
if(K8)L8=a;else{I8(a.id);var c=new e8(q8,a,y8());c.connect(b,J8());c.subscribe("beforeDisconnect",function(d){O4("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){B8()&&F8(null)});
F8(c)}},Iqa=function(){var a=x8();
a?(u8("Resume connection to: "+V4(a)),E8(a,0)):(h5(),I7(),u8("Skipping connecting because no session screen found."))},Fqa=function(){var a=y8();
if(g.Zb(a)){a=c5();var b=g.Vx("yt-remote-session-name")||"",c=g.Vx("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},y8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},Hqa=function(a){a?(g.Ux("yt-remote-session-app",a.app),g.Ux("yt-remote-session-name",a.name)):(P4("yt-remote-session-app"),P4("yt-remote-session-name"));
g.Ga("yt.mdx.remote.channelParams_",a,void 0)},M8=function(a,b,c){g.F.call(this);
this.u=a;this.i=b;this.l=new g.Is(this);g.H(this,this.l);this.l.J(b,"onCaptionsTrackListChanged",this.bI);this.l.J(b,"captionschanged",this.bH);this.l.J(b,"captionssettingschanged",this.pz);this.l.J(b,"videoplayerreset",this.an);this.l.J(b,"mdxautoplaycancel",this.aB);this.P=this.l.J(b,"onVolumeChange",this.Lx);this.C=!1;this.g=c;c.subscribe("proxyStateChange",this.Zx,this);c.subscribe("remotePlayerChange",this.bk,this);c.subscribe("remoteQueueChange",this.an,this);c.subscribe("autoplayUpNext",this.Bx,
this);c.subscribe("previousNextChange",this.Wx,this);c.subscribe("nowAutoplaying",this.Sx,this);c.subscribe("autoplayDismissed",this.Ax,this);this.suggestion=null;this.D=new g.tt(64);this.o=new g.I(this.nz,500,this);g.H(this,this.o);this.w=new g.I(this.oz,1E3,this);g.H(this,this.w);this.I=new q5(this.GL,0,this);g.H(this,this.I);this.B={};this.R=new g.I(this.Qz,1E3,this);g.H(this,this.R);this.G=new g.hl(this.yE,1E3,this);g.H(this,this.G);this.M=g.Ia;this.pz();this.an();this.bk()},N8=function(a,b){var c=
a.u,d=a.i.getVideoData().lengthSeconds;
c.R=b||0;c.player.N("progresssync",b,d)},P8=function(a){N8(a,0);
a.o.stop();O8(a,new g.tt(64))},R8=function(a,b){if(Q8(a)&&!a.C){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.ec(c,b));a.g.ez(a.i.getVideoData(1).videoId,c);a.B=X7(a.g).g}},S8=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Qa;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.ze,K4(c));O8(a,new g.tt(1))},T8=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{wP:1});
c&&c.length?(a.i.setOption("captions","track",b),a.C=!1):(a.i.loadModule("captions"),a.C=!0)}else a.i.setOption("captions","track",{})},Q8=function(a){return X7(a.g).videoId==a.i.getVideoData(1).videoId},O8=function(a,b){a.w.stop();
var c=a.D;if(!g.At(c,b)){var d=g.R(b,2);d!=g.R(a.D,2)&&g.SR(a.i.app,d);a.D=b;U8(a.u,c,b)}},V8=function(){g.T.call(this,{A:"div",
F:"ytp-mdx-popup-dialog",K:{role:"dialog"},H:[{A:"div",F:"ytp-mdx-popup-dialog-inner-content",H:[{A:"div",F:"ytp-mdx-popup-title",T:"\u0412\u044b \u0432\u044b\u0448\u043b\u0438 \u0438\u0437 \u0430\u043a\u043a\u0430\u0443\u043d\u0442\u0430"},{A:"div",F:"ytp-mdx-popup-description",T:'\u0420\u043e\u043b\u0438\u043a\u0438, \u043a\u043e\u0442\u043e\u0440\u044b\u0435 \u0432\u044b \u043f\u043e\u0441\u043c\u043e\u0442\u0440\u0438\u0442\u0435, \u043c\u043e\u0433\u0443\u0442 \u0431\u044b\u0442\u044c \u0434\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u044b \u0432 \u0438\u0441\u0442\u043e\u0440\u0438\u044e \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0430 \u043d\u0430 \u0442\u0435\u043b\u0435\u0432\u0438\u0437\u043e\u0440\u0435, \u0447\u0442\u043e \u0441\u043a\u0430\u0436\u0435\u0442\u0441\u044f \u043d\u0430 \u0440\u0435\u043a\u043e\u043c\u0435\u043d\u0434\u0430\u0446\u0438\u044f\u0445. \u0427\u0442\u043e\u0431\u044b \u044d\u0442\u043e\u0433\u043e \u0438\u0437\u0431\u0435\u0436\u0430\u0442\u044c, \u0432\u044b\u0431\u0435\u0440\u0438\u0442\u0435 "\u041e\u0442\u043c\u0435\u043d\u0430" \u0438 \u0432\u043e\u0439\u0434\u0438\u0442\u0435 \u0432 \u0430\u043a\u043a\u0430\u0443\u043d\u0442 \u043d\u0430 \u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440\u0435.'},
{A:"div",F:"ytp-mdx-privacy-popup-buttons",H:[{A:"button",U:["ytp-button","ytp-mdx-privacy-popup-cancel"],T:"\u041e\u0442\u043c\u0435\u043d\u0430"},{A:"button",U:["ytp-button","ytp-mdx-privacy-popup-confirm"],T:"\u041e\u041a"}]}]}]});this.l=new g.eL(this,250);g.H(this,this.l);this.B=this.i["ytp-mdx-privacy-popup-cancel"];this.J(this.B,"click",this.o);this.u=this.i["ytp-mdx-privacy-popup-confirm"];this.J(this.u,"click",this.w)},X8=function(a){g.T.call(this,{A:"div",
F:"ytp-remote",H:[{A:"div",F:"ytp-remote-display-status",H:[{A:"div",F:"ytp-remote-display-status-icon",H:[g.gL()]},{A:"div",F:"ytp-remote-display-status-text",T:"{{statustext}}"}]}]});this.l=new g.eL(this,250);g.H(this,this.l);this.o=a;this.J(a,"presentingplayerstatechange",this.u);W8(this,g.bK(a))},W8=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.R(b,128)?g.LL('\u041e\u0448\u0438\u0431\u043a\u0430 \u043d\u0430 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0435 "$RECEIVER_NAME"',c):g.Bt(b)||g.R(b,4)?g.LL('\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435 \u043d\u0430 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0435 "$RECEIVER_NAME"',c):g.LL('\u0423\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043e \u043f\u043e\u0434\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u0435 \u043a \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0443 "$RECEIVER_NAME"',
c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},Y8=function(a,b){g.HN.call(this,"\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u043e \u0434\u043b\u044f \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0430",0,a,b);
this.l=a;this.B={};this.J(a,"onMdxReceiversChange",this.I);this.J(a,"presentingplayerstatechange",this.I);this.I()},Z8=function(a){g.QO.call(this,a);
this.i={key:X4(),name:"\u042d\u0442\u043e\u0442 \u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440"};this.u=null;this.o=[];this.M=this.g=null;this.G=[this.i];this.l=this.i;this.B=new g.tt(64);this.R=0;this.D=-1;this.w=null;if(!g.Yy(this.player.L())){a=this.player;var b=g.JC(a);b&&(b=b.Im())&&(b=new Y8(a,b),g.H(this,b));b=new X8(a);g.H(this,b);g.tK(a,b.element,4);this.w=new V8;g.H(this,this.w);g.tK(a,this.w.element,4);this.I=!!x8()}this.C=null},$8=function(a){a.C&&(a.player.removeEventListener("presentingplayerstatechange",
a.C),a.C=null)},U8=function(a,b,c){a.B=c;
a.player.N("presentingplayerstatechange",new g.$C(c,b))},a9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)D8();
else{var c;(c=!g.P(a.player.L().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.to("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.to("SESSION_INDEX")&&!g.to("LOGGED_IN")))||a.I||!a.w);if(c?0:"WEB"==a.player.L().deviceParams.c||"WEB_EMBEDDED_PLAYER"==a.player.L().deviceParams.c)g.Bt(g.bK(a.player))?a.player.pauseVideo():(a.C=(0,g.x)(a.FK,a),a.player.addEventListener("presentingplayerstatechange",a.C)),a.w&&a.w.l.show(),B8()||(K8=!0);a.l=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);
var e=c.videoId;if(d||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.ra(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.ze,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=K4(c))&&(d.locationInfo=c);c=d}else c=null;u8("Connecting to: "+g.Bj(b));"cast-selector-receiver"==b.key?(w8(c||null),K7()?D7().setLaunchParams(c||null):A7("setLaunchParams called before ready.")):
!c&&G8()&&t8()==b.key?O4("yt-remote-connection-change",!0):(D8(),w8(c||null),c=s8().Kd(),(c=Z4(c,b.key))&&E8(c,1))}},K5={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},J5={"'":"\\'"},Mqa={},Rpa={BM:"atp",OO:"ska",DO:"que",gO:"mus",NO:"sus",yN:"dsp",KO:"seq"};
Q4.prototype.Rf=function(){var a=new Q4({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var i5,b5="",Ypa=k5("loadCastFramework")||k5("loadCastApplicationFramework"),tqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.Ta(q5,g.F);g.h=q5.prototype;g.h.VB=function(a){this.o=arguments;this.g=!1;this.za?this.l=(0,g.A)()+this.Rc:this.za=g.fl(this.u,this.Rc)};
g.h.stop=function(){this.za&&(g.u.clearTimeout(this.za),this.za=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.w.apply(null,this.o)))};
g.h.V=function(){this.stop();q5.wb.V.call(this)};
g.h.WB=function(){this.l?(this.za=g.fl(this.u,this.l-(0,g.A)()),this.l=null):(this.za=null,this.i?this.g=!0:(this.g=!1,this.w.apply(null,this.o)))};s5.prototype.stringify=function(a){return g.u.JSON.stringify(a,void 0)};
s5.prototype.parse=function(a){return g.u.JSON.parse(a,void 0)};t5.prototype.g=null;t5.prototype.getOptions=function(){var a;(a=this.g)||(a={},v5(this)&&(a[0]=!0,a[1]=!0),a=this.g=a);return a};var b9;g.Ta(u5,t5);b9=new u5;g.h=x5.prototype;g.h.Mg=null;g.h.ne=!1;g.h.Fi=null;g.h.ks=null;g.h.oi=null;g.h.Jh=null;g.h.Kf=null;g.h.rg=null;g.h.eh=null;g.h.pc=null;g.h.Ek=0;g.h.re=null;g.h.Mn=null;g.h.cg=null;g.h.rj=-1;g.h.Zy=!0;g.h.Bg=!1;g.h.wp=0;g.h.fn=null;var E5={},C5={};g.h=x5.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.RK=function(a){a=a.target;var b=this.fn;b&&3==a6(a)?b.Sl():this.Yz(a)};
g.h.Yz=function(a){try{if(a==this.pc)a:{var b=a6(this.pc),c=this.pc.w,d=this.pc.getStatus();if(g.Jd&&!g.od(10)||g.Ld&&!g.ld("420+")){if(4>b)break a}else if(3>b||3==b&&!g.$f&&!e6(this.pc))break a;this.Bg||4!=b||7==c||(8==c||0>=d?this.g.me(3):this.g.me(2));O5(this);var e=this.pc.getStatus();this.rj=e;var f=e6(this.pc);(this.ne=200==e)?(4==b&&G5(this),this.u?(I5(this,b,f),g.$f&&this.ne&&3==b&&(this.ba.ea(this.i,"tick",this.LK),this.i.start())):F5(this,f),this.ne&&!this.Bg&&(4==b?this.g.Xm(this):(this.ne=
!1,B5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.cg=3,D5(13)):(this.cg=0,D5(14)),G5(this),H5(this))}}catch(k){this.pc&&e6(this.pc)}finally{}};
g.h.LK=function(){var a=a6(this.pc),b=e6(this.pc);this.Ek<b.length&&(O5(this),I5(this,a,b),this.ne&&4!=a&&B5(this))};
g.h.gK=function(a){N5((0,g.x)(this.fK,this,a),0)};
g.h.fK=function(a){this.Bg||(O5(this),F5(this,a),B5(this))};
g.h.hy=function(a){N5((0,g.x)(this.eK,this,a),0)};
g.h.eK=function(a){this.Bg||(G5(this),this.ne=a,this.g.Xm(this),this.g.me(4))};
g.h.cancel=function(){this.Bg=!0;G5(this)};
g.h.pK=function(){this.Fi=null;var a=(0,g.A)();0<=a-this.ks?(2!=this.Jh&&this.g.me(3),G5(this),this.cg=2,D5(18),H5(this)):M5(this,this.ks-a)};
g.h.getLastError=function(){return this.cg};g.h=S5.prototype;g.h.tp=null;g.h.Ad=null;g.h.gn=!1;g.h.bv=null;g.h.Dl=null;g.h.Vp=null;g.h.vp=null;g.h.Zd=null;g.h.qf=-1;g.h.qj=null;g.h.Ri=null;g.h.connect=function(a){this.vp=a;a=T5(this.g,null,this.vp);D5(3);this.bv=(0,g.A)();var b=this.g.C;null!=b?(this.qj=b[0],(this.Ri=b[1])?(this.Zd=1,U5(this)):(this.Zd=2,W5(this))):(J4(a,"MODE","init"),this.Ad=new x5(this,void 0,void 0,void 0),this.Ad.Mg=this.tp,A5(this.Ad,a,!1,null,!0),this.Zd=0)};
g.h.bB=function(a){if(a)this.Zd=2,W5(this);else{D5(4);var b=this.g;b.we=b.Qf.qf;y6(b,9)}a&&this.me(2)};
g.h.Qo=function(a){return this.g.Qo(a)};
g.h.abort=function(){this.Ad&&(this.Ad.cancel(),this.Ad=null);this.qf=-1};
g.h.av=function(){return!1};
g.h.ay=function(a,b){this.qf=a.rj;if(0==this.Zd)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.we=this.qf;y6(c,2);return}this.qj=c[0];this.Ri=c[1]}else c=this.g,c.we=this.qf,y6(c,2);else if(2==this.Zd)if(this.gn)D5(7),this.Vp=(0,g.A)();else if("11111"==b){if(D5(6),this.gn=!0,this.Dl=(0,g.A)(),c=this.Dl-this.bv,!g.Jd||g.od(10)||500>c)this.qf=200,this.Ad.cancel(),D5(12),V5(this.g,this,!0)}else D5(8),this.Dl=this.Vp=(0,g.A)(),this.gn=!1};
g.h.Xm=function(){this.qf=this.Ad.rj;if(this.Ad.ne)0==this.Zd?this.Ri?(this.Zd=1,U5(this)):(this.Zd=2,W5(this)):2==this.Zd&&((!g.Jd||g.od(10)?!this.gn:200>this.Vp-this.Dl)?(D5(11),V5(this.g,this,!1)):(D5(12),V5(this.g,this,!0)));else{0==this.Zd?D5(9):2==this.Zd&&D5(10);var a=this.g;this.Ad.getLastError();a.we=this.qf;y6(a,2)}};
g.h.qk=function(){return this.g.qk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.me=function(a){this.g.me(a)};g.Ta(X5,g.uk);var cqa=/^https?$/i,Nqa=["POST","PUT"];g.h=X5.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.D+"; newUri="+a);b=b?b.toUpperCase():"GET";this.D=a;this.o="";this.w=0;this.W=b;this.P=!1;this.l=!0;this.g=this.M?w5(this.M):w5(b9);this.R=this.M?this.M.getOptions():b9.getOptions();this.g.onreadystatechange=(0,g.x)(this.cv,this);try{N4(b6(this,"Opening Xhr")),this.aa=!0,this.g.open(b,String(a),!0),this.aa=!1}catch(f){N4(b6(this,"Error opening Xhr: "+f.message));$5(this,f);return}a=c||"";
var e=this.headers.clone();d&&Mpa(d,function(f,k){e.set(k,f)});
d=g.Ya(e.Wd(),bqa);c=g.u.FormData&&a instanceof g.u.FormData;!g.ab(Nqa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.X&&(this.g.responseType=this.X);"withCredentials"in this.g&&this.g.withCredentials!==this.S&&(this.g.withCredentials=this.S);try{d6(this),0<this.B&&(this.I=aqa(this.g),N4(b6(this,"Will abort after "+this.B+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.B,this.g.ontimeout=(0,g.x)(this.dv,this)):this.G=g.fl(this.dv,this.B,this)),N4(b6(this,"Sending request")),this.C=!0,this.g.send(a),this.C=!1}catch(f){N4(b6(this,"Send error: "+f.message)),$5(this,f)}};
g.h.dv=function(){"undefined"!=typeof g.fZ&&this.g&&(this.o="Timed out after "+this.B+"ms, aborting",this.w=8,b6(this,this.o),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.l&&(b6(this,"Aborting"),this.l=!1,this.u=!0,this.g.abort(),this.u=!1,this.w=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Z5(this))};
g.h.V=function(){this.g&&(this.l&&(this.l=!1,this.u=!0,this.g.abort(),this.u=!1),Z5(this,!0));X5.wb.V.call(this)};
g.h.cv=function(){this.fa()||(this.aa||this.C||this.u?c6(this):this.fJ())};
g.h.fJ=function(){c6(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<a6(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.Da(this.o)?this.o:String(this.o)};g.h=f6.prototype;g.h.dj=null;g.h.td=null;g.h.Nb=null;g.h.rp=null;g.h.Fl=null;g.h.Dt=null;g.h.Tl=null;g.h.Wj=0;g.h.vG=0;g.h.Oc=null;g.h.Xf=null;g.h.bf=null;g.h.Fg=null;g.h.Qf=null;g.h.Kn=null;g.h.Vh=-1;g.h.Nv=-1;g.h.we=-1;g.h.Ch=0;g.h.wh=0;g.h.Cg=8;var z6=new g.uk;g.Ta(g6,g.Xj);g.Ta(h6,g.Xj);g.Ta(i6,g.Xj);g.h=f6.prototype;g.h.connect=function(a,b,c,d,e){D5(0);this.rp=b;this.dj=c||{};d&&g.Ca(e)&&(this.dj.OSID=d,this.dj.OAID=e);this.w?(N5((0,g.x)(this.Xt,this,a),100),o6(this)):this.Xt(a)};
g.h.Xt=function(a){this.Qf=new S5(this);this.Qf.tp=null;this.Qf.i=this.u;this.Qf.connect(a)};
g.h.av=function(){return 0==this.g};
g.h.gy=function(a){this.Xf=null;t6(this,a)};
g.h.fy=function(){this.bf=null;this.Nb=new x5(this,this.l,"rpc",this.B);this.Nb.Mg=null;this.Nb.wp=0;var a=this.Dt.clone();H4(a,"RID","rpc");H4(a,"SID",this.l);H4(a,"CI",this.Kn?"0":"1");H4(a,"AID",this.Vh);k6(this,a);if(!g.Jd||g.od(10))H4(a,"TYPE","xmlhttp"),A5(this.Nb,a,!0,this.Tl,!1);else{H4(a,"TYPE","html");var b=this.Nb,c=!!this.Tl;b.Jh=3;b.Kf=I4(a.clone());L5(b,c)}};
g.h.ay=function(a,b){if(0!=this.g&&(this.Nb==a||this.td==a))if(this.we=a.rj,this.td==a&&3==this.g)if(7<this.Cg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.La(c)&&3==c.length)if(0==c[0])a:{if(!this.bf){if(this.Nb)if(this.Nb.oi+3E3<this.td.oi)p6(this),this.Nb.cancel(),this.Nb=null;else break a;w6(this);D5(19)}}else this.Nv=c[1],0<this.Nv-this.Vh&&37500>c[2]&&this.Kn&&0==this.wh&&!this.Fg&&(this.Fg=N5((0,g.x)(this.XG,this),6E3));else y6(this,11)}else b!=Mqa.ZM.g&&y6(this,11);else if(this.Nb==a&&
p6(this),!g.yb(b)){c=this.u.parse(b);g.La(c);for(var d=0;d<c.length;d++){var e=c[d];this.Vh=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.Tl=e[2],e=e[3],null!=e?this.Cg=e:this.Cg=6,this.g=3,this.Oc&&this.Oc.Rt(),this.Dt=T5(this,this.qk()?this.Tl:null,this.rp),u6(this)):"stop"==e[0]&&y6(this,7):3==this.g&&("stop"==e[0]?y6(this,7):"noop"!=e[0]&&this.Oc&&this.Oc.Qt(e),this.wh=0)}}};
g.h.XG=function(){null!=this.Fg&&(this.Fg=null,this.Nb.cancel(),this.Nb=null,w6(this),D5(20))};
g.h.Xm=function(a){if(this.Nb==a){p6(this);this.Nb=null;var b=2}else if(this.td==a)this.td=null,b=1;else return;this.we=a.rj;if(0!=this.g)if(a.ne)1==b?(b=(0,g.A)()-a.oi,z6.dispatchEvent(new h6(z6,a.eh?a.eh.length:0,b,this.Ch)),n6(this),this.o.length=0):u6(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.we)){if(d=1==b)this.td||this.Xf||1==this.g||2<=this.Ch?d=!1:(this.Xf=N5((0,g.x)(this.gy,this,a),v6(this,this.Ch)),this.Ch++,d=!0);d=!(d||2==b&&w6(this))}if(d)switch(c){case 1:y6(this,
5);break;case 4:y6(this,10);break;case 3:y6(this,6);break;case 7:y6(this,12);break;default:y6(this,2)}}};
g.h.vB=function(a){if(!g.ab(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.xL=function(a){a?D5(2):(D5(1),x6(this,8))};
g.h.Qo=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new X5;a.S=!1;return a};
g.h.isActive=function(){return!!this.Oc&&this.Oc.isActive(this)};
g.h.me=function(a){z6.dispatchEvent(new i6(z6,a))};
g.h.qk=function(){return!(!g.Jd||g.od(10))};
g.h=A6.prototype;g.h.Rt=function(){};
g.h.Qt=function(){};
g.h.Pt=function(){};
g.h.Jo=function(){};
g.h.Du=function(){return{}};
g.h.isActive=function(){return!0};g.h=B6.prototype;g.h.isEmpty=function(){return g.bb(this.g)&&g.bb(this.i)};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.ab(this.g,a)||g.ab(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.rna)(b,a);0<=c?(g.db(b,c),b=!0):b=!1;return b||g.eb(this.i,a)};
g.h.wd=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};g.Ta(C6,g.F);g.h=C6.prototype;g.h.XJ=function(){this.Rc=Math.min(3E5,2*this.Rc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Rc+15E3*Math.random();g.an(this.g,a);this.i=(0,g.A)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Rc=5E3};g.Ta(D6,A6);g.h=D6.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.yf=function(a){return this.l.Ng(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.bb||(this.bb=!0,g.Ai(this.l),E6(this),g.Ai(this.i),this.i=null)};
g.h.fa=function(){return this.bb};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.D="";this.i.stop();this.u=a||null;this.o=b||0;a=this.G+"/test";b=this.G+"/bind";var d=new f6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Oc=null);d.Oc=this;this.g=d;e?this.g.connect(a,b,this.w,e.l,e.Vh):c?this.g.connect(a,b,this.w,c.sessionId,c.arrayId):this.g.connect(a,b,this.w)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.B.push(c):F6(this)&&q6(this.g,c)};
g.h.Rt=function(){this.i.reset();this.u=null;this.o=0;if(this.B.length){var a=this.B;this.B=[];for(var b=0,c=a.length;b<c;++b)q6(this.g,a[b])}this.N("handlerOpened")};
g.h.Pt=function(a){var b=2==a&&401==this.g.we;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.Jo=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.B.push(d)}};
g.h.Du=function(){var a={v:2};this.D&&(a.gsessionid=this.D);0!=this.o&&(a.ui=""+this.o);0!=this.C&&(a.ui=""+this.C);this.u&&g.ec(a,this.u);return a};
g.h.Qt=function(a){"S"==a[0]?this.D=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),m6(this.g)):this.N("handlerMessage",new eqa(a[0],a[1]))};
g.h.bL=function(){this.i.isActive();var a=this.g,b=0;a.Nb&&b++;a.td&&b++;0==b&&this.connect(this.u,this.o)};G6.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
G6.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
G6.prototype.u=function(a){a(Error("request timed out"))};var kqa=(0,g.A)(),L6=null,P6=Array(50),O6=-1,Q6=!1;g.Ta(R6,g.O);R6.prototype.Kd=function(){return this.g};
R6.prototype.contains=function(a){return!!Y4(this.g,a)};
R6.prototype.get=function(a){return a?Z4(this.g,a):null};
R6.prototype.info=function(a){N6(this.B,a)};g.r(T6,g.O);g.h=T6.prototype;g.h.start=function(){!this.g&&isNaN(this.za)&&this.cA()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.za)||(g.Do(this.za),this.za=NaN)};
g.h.V=function(){this.stop();g.O.prototype.V.call(this)};
g.h.cA=function(){this.za=NaN;this.g=g.zp(H6(this.w,"/pairing/get_screen"),{method:"POST",rb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.x)(this.ZL,this),onError:(0,g.x)(this.YL,this),Nd:(0,g.x)(this.aM,this)})};
g.h.ZL=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new R4(c))};
g.h.YL=function(a){this.g=null;a.status&&404==a.status?this.i>=c9.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=c9[this.i],this.za=g.Bo((0,g.x)(this.cA,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.aM=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};
var c9=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ta(V6,R6);g.h=V6.prototype;g.h.start=function(){U6(this)&&this.N("screenChange");!g.Vx("yt-remote-lounge-token-expiration")&&W6(this);g.Do(this.i);this.i=g.Bo((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){U6(this);S6(this,a);X6(this,!1);this.N("screenChange");b(a);a.token||W6(this)};
g.h.remove=function(a,b){var c=U6(this);mqa(this,a)&&(X6(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.Gn=function(a,b,c,d){var e=U6(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,X6(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.V=function(){g.Do(this.i);V6.wb.V.call(this)};
g.h.hC=function(a){U6(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}X6(this,!b);b&&N6(this.B,"Missed "+b+" lounge tokens.")};
g.h.gC=function(a){N6(this.B,"Requesting lounge tokens failed: "+a)};g.r(Z6,g.O);g.h=Z6.prototype;g.h.start=function(){var a=parseInt(g.Vx("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.A)()-144E5<a?0:a)?b7(this):(this.o=(0,g.A)()+3E5,g.Ux("yt-remote-fast-check-period",this.o),this.ur())};
g.h.isEmpty=function(){return g.Zb(this.g)};
g.h.update=function(){Y6("Updating availability on schedule.");var a=this.w(),b=g.Nb(this.g,function(c,d){return c&&!!Z4(a,d)},this);
a7(this,b)};
g.h.V=function(){g.Do(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.O.prototype.V.call(this)};
g.h.ur=function(){g.Do(this.l);this.l=NaN;this.i&&this.i.abort();var a=c7(this);if(L4(a)){var b=H6(this.u,"/pairing/get_screen_availability");this.i=I6(this.u,b,{lounge_token:g.Tb(a).join(",")},(0,g.x)(this.BJ,this,a),(0,g.x)(this.AJ,this))}else a7(this,{}),b7(this)};
g.h.BJ=function(a,b){this.i=null;var c=g.Tb(c7(this));if(g.sb(c,g.Tb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;a7(this,d);b7(this)}else this.Gb("Changing Screen set during request."),this.ur()};
g.h.AJ=function(a){this.Gb("Screen availability failed: "+a);this.i=null;b7(this)};
g.h.Gb=function(a){N6("OnlineScreenService",a)};g.Ta(d7,R6);g.h=d7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.Gn=function(a,b,c,d){this.l.contains(a)?this.l.Gn(a,b,c,d):(a="Updating name of unknown screen: "+a.name,N6(this.B,a),d(Error(a)))};
g.h.Kd=function(a){return a?this.g:g.gb(this.g,(0,g.Vd)(this.o,function(b){return!this.contains(b)},this))};
g.h.dA=function(){return(0,g.Vd)(this.Kd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.eA=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new T6(this.w,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.Ai(f);d(e7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.Ai(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.cM=function(a,b,c,d){g.zp(H6(this.w,"/pairing/get_screen"),{method:"POST",rb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new R4(f.screen||{});if(!k.name||g7(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);g7(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(e7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Nd:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.Ai(this.l);g.Ai(this.i);d7.wb.V.call(this)};
g.h.oC=function(){h7(this);this.N("screenChange");this.i.update()};
d7.prototype.dispose=d7.prototype.dispose;g.Ta(j7,g.O);g.h=j7.prototype;g.h.Zm=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Md=function(a){this.fa()||(a&&k7(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){N6(this.R,a)};
g.h.gA=function(){return null};
g.h.Cr=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){k7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.Cr("");j7.wb.V.call(this)};g.Ta(m7,j7);g.h=m7.prototype;g.h.Br=function(a){if(this.g){if(this.g==a)return;k7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.w);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.w);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);qqa(this)};
g.h.Wh=function(a){this.info("launchWithParams no-op for Cast: "+g.Bj(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.x)(function(){this.Md()},this),(0,g.x)(function(){this.Md(Error("Failed to stop receiver app."))},this)):this.Md(Error("Stopping cast device witout session."))};
g.h.Cr=g.Ia;g.h.V=function(){this.info("disposeInternal");g.Do(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.w),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;m7.wb.V.call(this)};
g.h.AK=function(a,b){if(!this.fa())if(b){var c=r5(b);if(g.Oa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Bj(c));switch(d){case "mdxSessionStatus":l7(this,c.screenId);break;default:k7(this,"Unknown youtube message: "+d)}}else k7(this,"Unable to parse message.")}else k7(this,"No data in message.")};
g.h.Vu=function(a,b,c,d){f7(this.D,this.i.label,a,this.i.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(k7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Bo((0,g.x)(this.Vu,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.gA=function(){return this.g};
g.h.dM=function(a){this.fa()||a||(k7(this,"Cast session died."),this.Md())};g.Ta(n7,j7);g.h=n7.prototype;g.h.Br=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.Wh=function(a){this.u=a;this.B()};
g.h.stop=function(){this.g();this.g=g.Ia;g.Do(this.w);this.o?this.o.stop((0,g.x)(this.Md,this,null),(0,g.x)(this.Md,this,"Failed to stop DIAL device.")):this.Md()};
g.h.V=function(){this.g();this.g=g.Ia;g.Do(this.w);this.o&&this.o.removeUpdateListener(this.I);this.o=null;n7.wb.V.call(this)};
g.h.gM=function(a){this.fa()||a||(k7(this,"DIAL session died."),this.g(),this.g=g.Ia,this.Md())};
g.h.Hp=function(a){this.G=X4();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,p7(this));a(b);o7(this)}else this.B=(0,g.x)(function(){g.Do(this.w);this.B=g.Ia;this.w=NaN;var c=new chrome.cast.DialLaunchResponse(!0,p7(this));a(c);o7(this)},this),this.w=g.Bo((0,g.x)(function(){this.B()},this),100)};
g.h.IC=function(a,b,c){f7(this.D,this.C.receiver.label,a,this.i.friendlyName,(0,g.x)(function(d){d&&d.token?(this.Zm(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Hp(b,c)},this),(0,g.x)(function(d){k7(this,"Failed to get DIAL screen: "+d);
this.Hp(b,c)},this))};g.Ta(q7,j7);q7.prototype.stop=function(){this.Md()};
q7.prototype.Br=g.Ia;q7.prototype.Wh=function(){g.Do(this.g);this.g=NaN;var a=Z4(this.D.Kd(),this.i.label);a?this.Zm(a):this.Md(Error("No such screen"))};
q7.prototype.V=function(){g.Do(this.g);this.g=NaN;q7.wb.V.call(this)};g.Ta(r7,g.O);g.h=r7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.B);this.C||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.kJ,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.dy,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.wH,this);chrome.cast.initialize(c,(0,g.x)(function(){this.fa()||
(chrome.cast.addReceiverActionListener(this.o),hqa(),this.i.subscribe("onlineScreenChange",(0,g.x)(this.fA,this)),this.l=w7(this),chrome.cast.setCustomReceivers(this.l,g.Ia,(0,g.x)(function(k){this.Gb("Failed to set initial custom receivers: "+g.Bj(k))},this)),this.N("yt-remote-cast2-availability-change",u7(this)),b(!0))},this),(0,g.x)(function(k){this.Gb("Failed to initialize API: "+g.Bj(k));
b(!1)},this))};
g.h.jL=function(a,b){t7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)t7("Unsetting old screen status: "+this.g.i.friendlyName),v7(this,null)}if(a&&b){if(!this.g){c=Z4(this.i.Kd(),a);if(!c){t7("setConnectedScreenStatus: Unknown screen.");return}var d=s7(this,c);d||(t7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ia,(0,g.x)(function(e){this.Gb("Failed to set initial custom receivers: "+g.Bj(e))},this)));
t7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);v7(this,new q7(this.i,d),!0)}this.g.Cr(b)}else t7("setConnectedScreenStatus: no screen.")};
g.h.kL=function(a){this.fa()?this.Gb("Setting connection data on disposed cast v2"):this.g?this.g.Wh(a):this.Gb("Setting connection data without a session")};
g.h.fM=function(){this.fa()?this.Gb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),v7(this,null)):t7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.dy,this),(0,g.x)(this.HJ,this))};
g.h.V=function(){this.i.unsubscribe("onlineScreenChange",(0,g.x)(this.fA,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.eb(g.w("yt.mdx.remote.debug.handlers_")||[],J6);g.Ai(this.g);r7.wb.V.call(this)};
g.h.Gb=function(a){N6("Controller",a)};
g.h.ey=function(a,b){this.g==a&&(b||v7(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.gJ=function(a,b){if(!this.fa())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),t7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)t7("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{t7("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:v7(this,
new q7(this.i,a));break;case chrome.cast.ReceiverType.DIAL:v7(this,new n7(this.i,a,this.w));break;case chrome.cast.ReceiverType.CAST:v7(this,new m7(this.i,a));break;default:this.Gb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Gb("Stopping receiver w/o session: "+a.friendlyName)}else this.Gb("onReceiverAction_ called without receiver.")};
g.h.wH=function(a){if(this.fa())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Gb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Gb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return t7("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Gb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);v7(this,new n7(this.i,b,this.w))}b=this.g;b.C=a;return b.C.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.IC,b,(b.C.extraData||{}).screenId||null)):new Promise((0,g.x)(b.Hp,b))};
g.h.dy=function(a){if(!this.fa()){t7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)t7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),v7(this,new m7(this.i,b),!0);else{this.Gb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=Z4(this.i.Kd(),c.label);d&&S4(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(t7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ai(this.g),this.g=new m7(this.i,b),this.g.subscribe("sessionScreen",(0,g.x)(this.ey,this,this.g)),this.g.Wh(null));this.g.Br(a)}}};
g.h.eM=function(){return this.g?this.g.gA():null};
g.h.HJ=function(a){this.fa()||(this.Gb("Failed to estabilish a session: "+g.Bj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&v7(this,null))};
g.h.kJ=function(a){t7("Receiver availability updated: "+a);if(!this.fa()){var b=u7(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;u7(this)!=b&&this.N("yt-remote-cast2-availability-change",u7(this))}};
g.h.fA=function(){this.fa()||(this.l=w7(this),t7("Updating custom receivers: "+g.Bj(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ia,(0,g.x)(function(){this.Gb("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",u7(this)))};
r7.prototype.setLaunchParams=r7.prototype.kL;r7.prototype.setConnectedScreenStatus=r7.prototype.jL;r7.prototype.stopSession=r7.prototype.fM;r7.prototype.getCastSession=r7.prototype.eM;r7.prototype.requestSession=r7.prototype.requestSession;r7.prototype.init=r7.prototype.init;r7.prototype.dispose=r7.prototype.dispose;var F7=[];N7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";O7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.xe=a.hasPrevious,this.hasNext=a.hasNext,this.B=a.playerTime,this.w=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.C=a.duration,this.D=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
N7.prototype.isAdPlaying=function(){return 1081==this.playerState};
N7.prototype.getDuration=function(){return this.u?this.C+P7(this):this.C};
N7.prototype.clone=function(){return new N7(T7(this))};g.r(W7,g.O);g.h=W7.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ia,d8(this,"play")):b8(this,"play"),a8(this,1,R7(X7(this))),this.N("remotePlayerChange")):Z7(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ia,d8(this,"pause")):b8(this,"pause"),a8(this,2,R7(X7(this))),this.N("remotePlayerChange")):Z7(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=X7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ia,d8(this,"seekTo",{newTime:a}))}else b8(this,"seekTo",{newTime:a});a8(this,3,a);this.N("remotePlayerChange")}else Z7(this,g.Ra(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ia,d8(this,"stopVideo")):b8(this,"stopVideo");var a=X7(this);a.index=-1;a.videoId="";O7(a);$7(this,a);this.N("remotePlayerChange")}else Z7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=X7(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.x)(function(){N6("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Gb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.x)(function(){N6("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Gb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);b8(this,"setVolume",e)}c.muted=b;c.volume=a;$7(this,c)}else Z7(this,g.Ra(this.setVolume,a,b))};
g.h.ez=function(a,b){if(1==this.g){var c=X7(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Bj(b.style),g.ec(d,c.g));b8(this,"setSubtitlesTrack",d);$7(this,c)}else Z7(this,g.Ra(this.ez,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();b8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=X7(this);d.audioTrackId=c;$7(this,d)}else Z7(this,g.Ra(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=X7(this);c=c||0;var m={videoId:a,currentIndex:c};S7(l,a,c);g.Ca(b)&&(Q7(l,b),m.currentTime=b);g.Ca(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Bj(k));b8(this,"setPlaylist",m);d||$7(this,l)};
g.h.bA=function(a,b){if(1==this.g){if(a&&b){var c=X7(this);S7(c,a,b);$7(this,c)}b8(this,"previous")}else Z7(this,g.Ra(this.bA,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=X7(this);S7(c,a,b);$7(this,c)}b8(this,"next")}else Z7(this,g.Ra(this.nextVideo,a,b))};
g.h.gu=function(){1==this.g?b8(this,"dismissAutoplay"):Z7(this,this.gu)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}g.O.prototype.dispose.call(this)};
g.h.V=function(){Y7(this);this.o=null;this.u.clear();V7(this,null);g.O.prototype.V.call(this)};
g.h.qs=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,g.bb(b.g)&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.dJ=function(a,b){this.N(a,b)};
g.h.dH=function(a){if(!a)this.Zj(null),V7(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=X7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)N6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,$7(this,b)}};
g.h.Zj=function(a){N6("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.C);if(this.i=a)this.i.addUpdateListener(this.C),c8(this),this.N("remotePlayerChange")};
g.h.cH=function(a){a?(c8(this),this.N("remotePlayerChange")):this.Zj(null)};
g.h.pH=function(){var a=J7();a&&V7(this,a)};
g.h.Gb=function(a){N6("CP",a)};g.r(e8,g.O);g.h=e8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ca(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ca(k)&&(l.currentIndex=k);c&&(this.Oa.listId=c);this.Oa.videoId=d;this.Oa.index=k||0;this.Oa.state=3;Q7(this.Oa,m);this.o="UNSUPPORTED";f8("Connecting with setPlaylist and params: "+g.Bj(l));this.g.connect({method:"setPlaylist",
params:g.Bj(l)},a,e5())}else f8("Connecting without params"),this.g.connect({},a,e5());xqa(this)};
g.h.dispose=function(){this.fa()||(this.N("beforeDispose"),g8(this,3));g.O.prototype.dispose.call(this)};
g.h.V=function(){h8(this);j8(this);i8(this);g.Do(this.B);this.B=NaN;g.Do(this.C);this.C=NaN;this.l=null;g.Zq(this.R);this.R.length=0;this.g.dispose();g.O.prototype.V.call(this);this.o=this.w=this.i=this.Oa=this.g=null};
g.h.ZB=function(){this.Ah(2)};
g.h.hH=function(){f8("Channel opened");this.I&&(this.I=!1,i8(this),this.G=g.Bo((0,g.x)(function(){f8("Timing out waiting for a screen.");this.Ah(1)},this),15E3));
Wpa(fqa(this.g),this.M)};
g.h.eH=function(){f8("Channel closed");isNaN(this.u)?h5(!0):h5();this.dispose()};
g.h.fH=function(a){h5();isNaN(this.kj())?(f8("Channel error: "+a+" without reconnection"),this.dispose()):(this.I=!0,f8("Channel error: "+a+" with reconnection in "+this.kj()+" ms"),g8(this,2))};
g.h.gH=function(a){a.params?f8("Received: action="+a.action+", params="+g.Bj(a.params)):f8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=r5(a.params.devices);this.i=(0,g.ee)(a,function(c){return new Q4(c)});
a=!!g.Ya(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
m8(this,a);break;case "loungeScreenDisconnected":g.fb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
m8(this,!1);break;case "remoteConnected":var b=new Q4(r5(a.params.device));g.Ya(this.i,function(c){return b?c.id==b.id:!1})||Jpa(this.i,b);
break;case "remoteDisconnected":b=new Q4(r5(a.params.device));g.fb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":n8(this,a);break;case "nowPlaying":Aqa(this,a);break;case "onStateChange":o8(this,a);break;case "onAdStateChange":Bqa(this,a);break;case "onVolumeChanged":Cqa(this,a);break;case "onSubtitlesTrackChanged":zqa(this,a);break;case "nowAutoplaying":Dqa(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.w=a.params.videoId||null;this.N("autoplayUpNext",this.w);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":Eqa(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:f8("Unrecognized action: "+a.action)}};
g.h.YK=function(){if(this.l){var a=this.l;this.l=null;this.Oa.videoId!=a&&k8(this,"getNowPlaying")}};
g.h.PB=function(){var a=3;this.fa()||(a=0,isNaN(this.kj())?F6(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
g.h.Ah=function(a){f8("Disconnecting with "+a);h8(this);this.N("beforeDisconnect",a);1==a&&h5();E6(this.g,a);this.dispose()};
g.h.OB=function(){var a=this.Oa;this.l&&(a=this.Oa.clone(),S7(a,this.l,a.index));return T7(a)};
g.h.lL=function(a){var b=new N7(a);b.videoId&&b.videoId!=this.Oa.videoId&&(this.l=b.videoId,g.Do(this.B),this.B=g.Bo((0,g.x)(this.YK,this),5E3));var c=[];this.Oa.listId==b.listId&&this.Oa.videoId==b.videoId&&this.Oa.index==b.index||c.push("remoteQueueChange");this.Oa.playerState==b.playerState&&this.Oa.volume==b.volume&&this.Oa.muted==b.muted&&R7(this.Oa)==R7(b)&&g.Bj(this.Oa.g)==g.Bj(b.g)||c.push("remotePlayerChange");this.Oa.reset(a);(0,g.z)(c,function(d){this.N(d)},this)};
g.h.Tu=function(){var a=this.g.w.id,b=g.Ya(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.kj=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.A)():NaN};
g.h.IB=function(){return this.o||"UNSUPPORTED"};
g.h.JB=function(){return this.w||""};
g.h.XL=function(){if(!isNaN(this.kj())){var a=this.g.i;g.bn(a.g);a.start()}};
g.h.gL=function(a,b){k8(this,a,b);l8(this)};
e8.prototype.subscribe=e8.prototype.subscribe;e8.prototype.unsubscribeByKey=e8.prototype.yf;e8.prototype.getProxyState=e8.prototype.PB;e8.prototype.disconnect=e8.prototype.Ah;e8.prototype.getPlayerContextData=e8.prototype.OB;e8.prototype.setPlayerContextData=e8.prototype.lL;e8.prototype.getOtherConnectedRemoteId=e8.prototype.Tu;e8.prototype.getReconnectTimeout=e8.prototype.kj;e8.prototype.getAutoplayMode=e8.prototype.IB;e8.prototype.getAutoplayVideoId=e8.prototype.JB;e8.prototype.reconnect=e8.prototype.XL;
e8.prototype.sendMessage=e8.prototype.gL;g.r(p8,R6);g.h=p8.prototype;g.h.Kd=function(a){return this.Qc.$_gs(a)};
g.h.contains=function(a){return!!this.Qc.$_c(a)};
g.h.get=function(a){return this.Qc.$_g(a)};
g.h.start=function(){this.Qc.$_st()};
g.h.add=function(a,b,c){this.Qc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Qc.$_r(a,b,c)};
g.h.Gn=function(a,b,c,d){this.Qc.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.i.length;a<b;++a)this.Qc.$_ubk(this.i[a]);this.i.length=0;this.Qc=null;R6.prototype.V.call(this)};
g.h.bM=function(){this.N("screenChange")};
g.h.GI=function(){this.N("onlineScreenChange")};
d7.prototype.$_st=d7.prototype.start;d7.prototype.$_gspc=d7.prototype.cM;d7.prototype.$_gsppc=d7.prototype.eA;d7.prototype.$_c=d7.prototype.contains;d7.prototype.$_g=d7.prototype.get;d7.prototype.$_a=d7.prototype.add;d7.prototype.$_un=d7.prototype.Gn;d7.prototype.$_r=d7.prototype.remove;d7.prototype.$_gs=d7.prototype.Kd;d7.prototype.$_gos=d7.prototype.dA;d7.prototype.$_s=d7.prototype.subscribe;d7.prototype.$_ubk=d7.prototype.yf;var L8=null,K8=!1,q8=null,r8=null,H8=null,v8=[];g.r(M8,g.F);g.h=M8.prototype;
g.h.V=function(){g.F.prototype.V.call(this);this.o.stop();this.w.stop();this.I.stop();this.M();this.g.unsubscribe("proxyStateChange",this.Zx,this);this.g.unsubscribe("remotePlayerChange",this.bk,this);this.g.unsubscribe("remoteQueueChange",this.an,this);this.g.unsubscribe("autoplayUpNext",this.Bx,this);this.g.unsubscribe("previousNextChange",this.Wx,this);this.g.unsubscribe("nowAutoplaying",this.Sx,this);this.g.unsubscribe("autoplayDismissed",this.Ax,this);this.g=this.u=null};
g.h.xw=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(Q8(this)){if(!X7(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==X7(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.G.Sl(c[0],c[1]);break;case "control_subtitles_set_track":R8(this,c[0]);break;case "control_set_audio_track":c=c[0],Q8(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();S8(this,0==c?void 0:c);break;case "control_seek":S8(this,c[0]);break;case "control_subtitles_set_track":R8(this,c[0]);break;case "control_set_audio_track":c=c[0],Q8(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.bH=function(a){this.I.VB(a)};
g.h.GL=function(a){this.xw("control_subtitles_set_track",g.Zb(a)?null:a)};
g.h.pz=function(){var a=this.i.getOption("captions","track");g.Zb(a)||R8(this,a)};
g.h.Lx=function(a){if(Q8(this)){this.g.unsubscribe("remotePlayerChange",this.bk,this);var b=Math.round(a.volume);a=!!a.muted;var c=X7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.R.start();this.g.subscribe("remotePlayerChange",this.bk,this)}};
g.h.bI=function(){g.Zb(this.B)||T8(this,this.B);this.C=!1};
g.h.Zx=function(a,b){this.w.stop();2==b&&this.oz()};
g.h.bk=function(){if(Q8(this)){this.o.stop();var a=X7(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.D=1;break;case 1082:case 1083:this.u.D=0;break;default:this.u.D=-1}switch(a.playerState){case 1081:case 1:O8(this,new g.tt(8));this.nz();break;case 1085:case 3:O8(this,new g.tt(9));break;case 1083:case 0:O8(this,new g.tt(2));this.G.stop();N8(this,this.i.getVideoData().lengthSeconds);break;case 1084:O8(this,new g.tt(4));break;case 2:O8(this,new g.tt(4));N8(this,R7(a));
break;case -1:O8(this,new g.tt(64));break;case -1E3:O8(this,new g.tt(128,{errorCode:"mdx.remoteerror",errorMessage:"\u0412\u0438\u0434\u0435\u043e \u043d\u0435\u0434\u043e\u0441\u0442\u0443\u043f\u043d\u043e \u0434\u043b\u044f \u0443\u0434\u0430\u043b\u0435\u043d\u043d\u043e\u0433\u043e \u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u044f."}))}a=X7(this.g).g;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&
a.kind==b.kind:1)||(this.B=a,T8(this,a));a=X7(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.R.isActive()||this.Qz()}else P8(this)};
g.h.Wx=function(){this.i.N("mdxpreviousnextchange")};
g.h.an=function(){Q8(this)||P8(this)};
g.h.aB=function(){this.g.gu()};
g.h.Bx=function(a){a&&!g.P(this.i.L().experiments,"disable_legacy_desktop_remote_queue")&&(a=g.zp("/watch_queue_ajax",{method:"GET",pd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.x)(this.iK,this)}))&&(this.M=(0,g.x)(a.abort,a))};
g.h.iK=function(a,b){var c=new g.DB(this.i.L(),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.Sx=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.Ax=function(){this.i.N("mdxautoplaycanceled")};
g.h.yE=function(a,b){-1==X7(this.g).playerState?S8(this,a):b&&this.g.seekTo(a)};
g.h.Qz=function(){if(Q8(this)){var a=X7(this.g);this.l.Sa(this.P);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.P=this.l.J(this.i,"onVolumeChange",this.Lx)}};
g.h.nz=function(){this.o.stop();if(!this.g.fa()){var a=X7(this.g);1==a.playerState&&O8(this,new g.tt(8));N8(this,R7(a));this.o.start()}};
g.h.oz=function(){this.w.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.w.start()};g.r(V8,g.T);V8.prototype.o=function(){O4("mdx-privacy-popup-cancel");this.l.hide()};
V8.prototype.w=function(){O4("mdx-privacy-popup-confirm");this.l.hide()};g.r(X8,g.T);X8.prototype.u=function(a){W8(this,a.state)};g.r(Y8,g.HN);Y8.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.B=g.ub(a,this.w,this),g.JN(this,(0,g.ee)(a,this.w)),a=this.l.getOption("remote","currentReceiver"),this.de(this.w(a)),this.enable(!0)):this.enable(!1)};
Y8.prototype.w=function(a){return a.key};
Y8.prototype.le=function(a){return"cast-selector-receiver"==a?"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c":this.B[a].name};
Y8.prototype.Jc=function(a){g.HN.prototype.Jc.call(this,a);this.l.setOption("remote","currentReceiver",this.B[a]);this.o.gb()};g.r(Z8,g.QO);g.h=Z8.prototype;
g.h.create=function(){Jqa(g.Jy(this.player.L()));this.o.push(g.Io("yt-remote-before-disconnect",this.YG,this));this.o.push(g.Io("yt-remote-connection-change",this.lJ,this));this.o.push(g.Io("yt-remote-receiver-availability-change",this.Xx,this));this.o.push(g.Io("yt-remote-auto-connect",this.jJ,this));this.o.push(g.Io("yt-remote-receiver-resumed",this.iJ,this));this.o.push(g.Io("mdx-privacy-popup-confirm",this.OK,this));this.o.push(g.Io("mdx-privacy-popup-cancel",this.NK,this));this.Xx()};
g.h.load=function(){this.player.cancelPlayback();g.QO.prototype.load.call(this);this.u=new M8(this,this.player,this.g);var a=(a=J8())?a.currentTime:0;var b=G8()?new W7(B8(),void 0):null;0==a&&b&&(a=R7(X7(b)));0!=a&&(this.R=a||0,this.player.N("progresssync",a,void 0));U8(this,this.B,this.B);g.ZR(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.l=this.i;g.Bi(this.u,this.g);this.g=this.u=null;g.QO.prototype.unload.call(this);g.ZR(this.player.app,5);$8(this)};
g.h.V=function(){g.Jo(this.o);g.QO.prototype.V.call(this)};
g.h.Mj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.u.xw.apply(this.u,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.D};
g.h.RB=function(){return this.loaded?this.u.suggestion:null};
g.h.xe=function(){return this.g?X7(this.g).xe:!1};
g.h.hasNext=function(){return this.g?X7(this.g).hasNext:!1};
g.h.getCurrentTime=function(){return this.R};
g.h.getProgressState=function(){var a=X7(this.g),b=this.player.getVideoData();return{allowSeeking:g.P(this.player.L().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.hc():!a.isAdPlaying()&&this.player.hc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+P7(a):a.l,isAtLiveHead:1>=(a.u?a.i+P7(a):a.i)-this.getCurrentTime(),loaded:a.D,seekableEnd:a.u?a.i+P7(a):a.i,seekableStart:0<a.o?a.o+P7(a):
a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.mE=function(){this.g&&this.g.bA()};
g.h.YG=function(a){1==a&&(this.M=this.g?X7(this.g):null)};
g.h.lJ=function(){var a=G8()?new W7(B8(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.M=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.Ai(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.M)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,R7(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Xx=function(){this.G=[this.i].concat(Kqa());var a=C8()||this.i;a9(this,a);this.player.ha("onMdxReceiversChange")};
g.h.FK=function(a){!this.I&&g.bD(a,8)&&(this.player.pauseVideo(),$8(this))};
g.h.jJ=function(){var a=C8();a9(this,a)};
g.h.iJ=function(){this.l=C8()};
g.h.OK=function(){this.I=!0;$8(this);K8=!1;L8&&E8(L8,1);L8=null};
g.h.NK=function(){this.I=!1;$8(this);a9(this,this.i);this.l=this.i;K8=!1;L8=null;this.player.playVideo()};
g.h.sc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?L7():a9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&L7(),!0):!1}};
g.h.nE=function(){b8(this.g,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Ne=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.dP.remote=Z8;})(_yt_player);
